spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:users_app
    username: alex
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true

server:
  port: ${PORT:0}
  servlet:
    context-path: /api/v1/auth

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

